.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gemoney_qt test_gemoney_qt
clean: FORCE
	$(MAKE) -C .. gemoney_qt_clean test_gemoney_qt_clean
check: FORCE
	$(MAKE) -C .. test_gemoney_qt_check
gemoney-qt gemoney-qt.exe: FORCE
	 $(MAKE) -C .. gemoney_qt
